CREATE TABLE MEDIA_INFO (

   ID  int NOT NULL AUTO_INCREMENT,
   MODEL_NAME  varchar(255) NOT NULL,
   CHANNEL_URL  varchar(255) NOT NULL,
   CHANNEL_NAME  varchar(255) NOT NULL,
   VIDEO_TITLE  varchar(255) NOT NULL,
   VIDEO_URL  varchar(255) NOT NULL,
   NUM_OF_REPLY  int NOT NULL,
   VIEWS  int NOT NULL,
   CRAWLED_DATE  DATE NOT NULL,
   LIKES  int NOT NULL,
   HATES  int NOT NULL,
   NUM_OF_SUBSCIBER  int NOT NULL,
   VIDEO_DESCRIPTION  varchar(2047) NOT NULL,
   VIDEO_POSTED_DATE  DATE NOT NULL,
   CATEGORY  varchar(255) NOT NULL,
   REPLY_REF_TABLE  varchar(255) NOT NULL,
   DA_CATEGORY varchar(255) NOT NULL,
  PRIMARY KEY(ID)

);

-- > Module Name
--  - Apple_iPhoneXS
--  - Samsung_Galaxy9
--  - LG_G7
--  - LG_Gram15_2018
--  - Samsung_Notebook9
--  - Samsung_GalaxyTab_S4
--  - Apple_iPad_S6
--  - Apple_iPad_Pro_S3

CREATE TABLE REPLY_REF_TABLE (

   ID  int NOT NULL AUTO_INCREMENT,
   CONTENT  varchar(2048) NOT NULL,
   CRAWLED_REPLY_DATE DATE NOT NULL,
   AUTHOR  varchar(255) NOT NULL,
   NOUNS_FROM_COMMENT varchar(1023) NOT NULL,
   SENTIMENTAL int,

  PRIMARY KEY (ID)

);

CREATE TABLE MODEL_INFO (
  ID int not NULL AUTO_INCREMENT,
  MODULE_NAME varchar(255) NOT NULL,
  PICTURE_URL varchar(1047) NOT NULL,
  COMPANY varchar(255) NOT NULL,
  MODULE_CODE varchar(255) NOT NULL,
  PRODUCT_TYPE_OF_MODULE varchar(255) NOT NULL,
  FREQUENCY_TABLE_NAME varchar(255) NOT NULL,
  CPU varchar(63) NOT NULL,
  MODEL_SIZE varchar(63) NOT NULL,
  MODEL_WEIGHT varchar(63) NOT NULL,
  DISPLAY_SIZE varchar(63) NOT NULL,
  DISPLAY_RESOLUTION varchar(63) NOT NULL,
  RAM varchar(63) NOT NULL,
  STORAGE varchar(63) NOT NULL,
  CAMERA varchar(63) NOT NULL,
  BATTERY varchar(63) NOT NULL,
  CHARGING_METHOD varchar(63) NOT NULL,
  SPEC_URL varchar(63) NOT NULL,
  FILTER_WORD varchar(127) NOT NULL,
  GOOD varchar(63) NOT NULL,
  BAD varchar(63) NOT NULL

  PRIMARY KEY (ID)
)

CREATE TABLE PRICE_INFO (
  MODEL_NAME varchar(255) NOT NULL,
  PRICE varchar(63) NOT NULL,
  CRAWLED_DATE DATE NOT NULL,

  PRIMARY KEY (MODEL_NAME)
)

CREATE TABLE LOG_INFO (
  WHOLE_DATA_COUNT int NOT NULL,
  CRAWLED_DATE DATE NOT NULL
)

CREATE TABLE DAY_COUNT(
  ACCESSED_COUNT int NOT NULL,
  ACCESSED_DATE DATE NOT NULL,

  PRIMARY KEY (ACCESSED_DATE)
)

CREATE TABLE $(MODEL_NAME)_FREQUENCY(
  WORD varchar(127) NOT NULL,
  FREQUENCY int NOT NULL,

  PRIMARY KEY (WORD)
)

CREATE TABLE SENTIMENTAL_GOOD_OR_BAD (

   ID  int NOT NULL,
   CONTENT  varchar(2048) NOT NULL,
   CRAWLED_REPLY_DATE DATE NOT NULL,
   AUTHOR  varchar(255) NOT NULL,
   NOUNS_FROM_COMMENT varchar(1023) NOT NULL,
   SENTIMENTAL int
)

