CREATE TABLE MEDIA_INFO (

   ID  int NOT NULL AUTO_INCREMENT,
   MODEL_NAME  varchar(255) NOT NULL,
   CHANNEL_URL  varchar(255) NOT NULL,
   CHANNEL_NAME  varchar(255) NOT NULL,
   VIDEO_TITLE  varchar(255) NOT NULL,
   VIDEO_URL  varchar(255) NOT NULL,
   NUM_OF_REPLY  int NOT NULL,
   VIEWS  int NOT NULL,
   CRAWLED_DATE  DATE NOT NULL,
   LIKES  int NOT NULL,
   HATES  int NOT NULL,
   NUM_OF_SUBSCIBER  int NOT NULL,
   VIDEO_DESCRIPTION  varchar(255) NOT NULL,
   VIDEO_POSTED_DATE  DATE NOT NULL,
   CATEGORY  varchar(255) NOT NULL,
   REPLY_REF_TABLE  varchar(255) NOT NULL,

  PRIMARY KEY(ID)

);

CREATE TABLE IphoneXS (

   ID  int NOT NULL AUTO_INCREMENT,
   CONTENT  varchar(2048) NOT NULL,
   CRAWLED_REPLY_DATE  DATE NOT NULL,
   AUTHOR  varchar(255) NOT NULL,
   LIKES  int NOT NULL,
   HATES  int NOT NULL,

  PRIMARY KEY (ID)

);
